runtime: python39  # assuming you're using Python 3.9
entrypoint: gunicorn -b :$PORT app:app  # 'app:app' assumes your Flask app is named 'app' in a file named 'app.py'
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
